# Autogen Installation


1. Create a venv
2. Create a requirements.txt
3. install autogen-agentchat autogen-core autogen-ext

# First Autogen Agent


In [7]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv('OPENAI_API_KEY')

# Connecting to the Model

In [9]:
model_client = OpenAIChatCompletionClient(model='gpt-4o',api_key=api_key)


In [10]:
agent_1 = AssistantAgent(name='my_assistant',model_client=model_client)

In [11]:
result = await agent_1.run(task='Tell me something about you?')

In [12]:
print(result)

messages=[TextMessage(id='714f62c3-d04b-4083-ba19-f7be07265189', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 25, 38, 211549, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='c246edfa-aa4b-42fa-9b64-9ae6ab725224', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=75), metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 25, 40, 380327, tzinfo=datetime.timezone.utc), content='I am an AI language model developed by OpenAI, designed to assist with a wide range of queries by providing information, answering questions, and helping with problem-solving. My training includes data up to October 2023, and I can perform tasks like summarizing text, providing explanations, and generating human-like text responses. Please let me know how I can assist you today!', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='714f62c3-d04b-4083-ba19-f7be07265189', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 25, 38, 211549, tzinfo=datetime.timezone.utc), content='Tell me something about you?', type='TextMessage'), TextMessage(id='c246edfa-aa4b-42fa-9b64-9ae6ab725224', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=75), metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 25, 40, 380327, tzinfo=datetime.timezone.utc), content='I am an AI language model developed by OpenAI, designed to assist with a wide range of queries by providing information, answering questions, and helping with problem-solving. My training includes data up to October 2023, and I can perform tasks like summarizing text, providing explanations, and generating human-like text responses. Please let me know how I can assist you today!', type='TextMessage')] stop_reason=None

In [13]:
result2 = await agent_1.run(task='What was my last question?')

In [14]:
result2

TaskResult(messages=[TextMessage(id='76d1e1aa-b951-46d2-9c60-ff1012276b25', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 27, 40, 688838, tzinfo=datetime.timezone.utc), content='What was my last question?', type='TextMessage'), TextMessage(id='5ea5301b-0980-47be-a864-a6ca7345aa70', source='my_assistant', models_usage=RequestUsage(prompt_tokens=132, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 27, 42, 61792, tzinfo=datetime.timezone.utc), content='Your last question was: "Tell me something about you?"', type='TextMessage')], stop_reason=None)

TaskResult(messages=[TextMessage(id='76d1e1aa-b951-46d2-9c60-ff1012276b25', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 27, 40, 688838, tzinfo=datetime.timezone.utc), content='What was my last question?', type='TextMessage'), TextMessage(id='5ea5301b-0980-47be-a864-a6ca7345aa70', source='my_assistant', models_usage=RequestUsage(prompt_tokens=132, completion_tokens=12), metadata={}, created_at=datetime.datetime(2025, 7, 5, 3, 27, 42, 61792, tzinfo=datetime.timezone.utc), content='Your last question was: "Tell me something about you?"', type='TextMessage')], stop_reason=None)